@server = http://localhost:31337

### Failure endpoint

GET {{server}}/api/v1/fail

### Success endpoint

GET {{server}}/api/v1/now

### Create task

POST {{server}}/api/v1/task/taskX
Content-Type: application/json

{
	"executable": "cmd",
	"arguments": "/c \"dir && pause\"",
	"environment": {
		"VAR": "7"
	},
}

### Get task

GET {{server}}/api/v1/task/task9

### Get tasks

GET {{server}}/api/v1/task

### Delete task

DELETE {{server}}/api/v1/task/task10

### Start task

PUT {{server}}/api/v1/task/taskX/start

### Restart task

PUT {{server}}/api/v1/task/taskZ/start?force=true


### Stop task

PUT {{server}}/api/v1/task/taskX/stop

### Get task logs

GET {{server}}/api/v1/task/taskX/logs
